name: Publish

on:
  workflow_run:
    workflows: ["Semantic Release"]
    types: [completed]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/
      - run: npm publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          registry-url: https://npm.pkg.github.com/
      - run: npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
